language: julia
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

before_install:
  - wget dist.neo4j.org/neo4j-community-3.3.5-unix.tar.gz
  - tar -xzf neo4j-community-3.3.5-unix.tar.gz
  - sed -i 's/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g' neo4j-community-3.3.5/conf/neo4j.conf
  - sed -i 's/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g' neo4j-community-3.3.5/conf/neo4j.conf
  - neo4j-community-3.3.5/bin/neo4j start

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("Neo4j"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Neo4j")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
